@startuml

title __SERVICE's Class Diagram__\n

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.AutorService {
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.CategoiaService {
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.CompraDetalleService {
            {abstract} + findAllByCompraId()
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.CompraService {
            {abstract} + findAllByBibliotecaId()
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.EstadisticaMisActividadesService {
            {abstract} + misActividades()
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.EstadisticaPrestamosPieChartService {
            {abstract} + prestamosPieChart()
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.KardexDetalleService {
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.KardexService {
            {abstract} + getByBibliotecaIdAndLibroId()
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.LibroAutorService {
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.LibroMasPrestadoPorBibliotecaService {
            {abstract} + libroMasPrestado()
            {abstract} + libroMasPrestadoPorBiblioteca()
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.LibroMateriaService {
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.LibroService {
            {abstract} + findByIsbn()
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.MateriaService {
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.PrestamoService {
            {abstract} + findAllByBibliotecaIdAndEstado()
            {abstract} + findAllByUsuarioIdAndEstado()
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.PrestamosPorMesService {
            {abstract} + prestamosPorMes()
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.ProveedorService {
        }
      }
    }
  }
  

  namespace  {
    namespace om.biblioteca.biblioteca {
      namespace service {
        interface com.biblioteca.biblioteca.service.UsuarioService {
            {abstract} + findByCorreoAndClave()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
